//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication.Implementation
{
    
    #region KundenItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class KundenItem :
        global::LightSwitchApplication.KundenItem.DetailsClass.IImplementation
    {
        partial void OnKunden_KundengruppeChanged()
        {
            this.___OnPropertyChanged("Kunden_Kundengruppe");
            this.___OnPropertyChanged("KundengruppenItem");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnVornameChanged()
        {
            this.___OnPropertyChanged("Vorname");
        }
        
        partial void OnNachnahmeChanged()
        {
            this.___OnPropertyChanged("Nachnahme");
        }
        
        partial void OnFirmaChanged()
        {
            this.___OnPropertyChanged("Firma");
        }
        
        partial void OnKundennummer_1Changed()
        {
            this.___OnPropertyChanged("Kundennummer_1");
        }
        
        partial void OnKundennummer_2Changed()
        {
            this.___OnPropertyChanged("Kundennummer_2");
        }
        
        partial void OnStraßeChanged()
        {
            this.___OnPropertyChanged("Straße");
        }
        
        partial void OnHausnummerChanged()
        {
            this.___OnPropertyChanged("Hausnummer");
        }
        
        partial void OnPLZChanged()
        {
            this.___OnPropertyChanged("PLZ");
        }
        
        partial void OnStadtChanged()
        {
            this.___OnPropertyChanged("Stadt");
        }
        
        partial void OnLandChanged()
        {
            this.___OnPropertyChanged("Land");
        }
        
        partial void OnTelefonnummerChanged()
        {
            this.___OnPropertyChanged("Telefonnummer");
        }
        
        partial void OnFaxnummerChanged()
        {
            this.___OnPropertyChanged("Faxnummer");
        }
        
        partial void OnEMailadresseChanged()
        {
            this.___OnPropertyChanged("EMailadresse");
        }
        
        partial void OnWebseiteChanged()
        {
            this.___OnPropertyChanged("Webseite");
        }
        
        partial void OnRabattChanged()
        {
            this.___OnPropertyChanged("Rabatt");
        }
        
        partial void OnZahlungszielChanged()
        {
            this.___OnPropertyChanged("Zahlungsziel");
        }
        
        partial void OnBemerkungenChanged()
        {
            this.___OnPropertyChanged("Bemerkungen");
        }
        
        partial void OnSonstigesChanged()
        {
            this.___OnPropertyChanged("Sonstiges");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.KundenItem.DetailsClass.IImplementation.KundengruppenItem
        {
            get
            {
                return this.KundengruppenItem;
            }
            set
            {
                this.KundengruppenItem = (global::LightSwitchApplication.Implementation.KundengruppenItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.KundengruppenItem> __KundengruppenItem
        {
            get
            {
                if (this.___KundengruppenItem == null)
                {
                    this.___KundengruppenItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.KundengruppenItem>(
                        this,
                        "KundengruppenItem",
                        new string[] { "Kunden_Kundengruppe" },
                        e => global::System.Object.Equals(e.Id, this.Kunden_Kundengruppe),
                        () => this._KundengruppenItem,
                        e => this._KundengruppenItem = e);
                }
                return this.___KundengruppenItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.KundengruppenItem> ___KundengruppenItem;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.KundenItem.DetailsClass.IImplementation.Adressen
        {
            get
            {
                return this.Adressen;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AdressenSetItem> __Adressen
        {
            get
            {
                if (this.___Adressen == null)
                {
                    this.___Adressen = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AdressenSetItem>(
                        this,
                        "Adressen",
                        () => this._Adressen,
                        e => global::System.Object.Equals(e.Kunden_Rechnungsadressen, this.Id));
                }
                return this.___Adressen;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.AdressenSetItem> ___Adressen;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.KundenItem.DetailsClass.IImplementation.Rechnungen
        {
            get
            {
                return this.Rechnungen;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Rechnungen> __Rechnungen
        {
            get
            {
                if (this.___Rechnungen == null)
                {
                    this.___Rechnungen = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Rechnungen>(
                        this,
                        "Rechnungen",
                        () => this._Rechnungen,
                        e => global::System.Object.Equals(e.Rechnungen_Kunden, this.Id));
                }
                return this.___Rechnungen;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Rechnungen> ___Rechnungen;
        
    }
    #endregion
    
    #region KundengruppenItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class KundengruppenItem :
        global::LightSwitchApplication.KundengruppenItem.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnBezeichnungChanged()
        {
            this.___OnPropertyChanged("Bezeichnung");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.KundengruppenItem.DetailsClass.IImplementation.Kunden
        {
            get
            {
                return this.Kunden;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.KundenItem> __Kunden
        {
            get
            {
                if (this.___Kunden == null)
                {
                    this.___Kunden = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.KundenItem>(
                        this,
                        "Kunden",
                        () => this._Kunden,
                        e => global::System.Object.Equals(e.Kunden_Kundengruppe, this.Id));
                }
                return this.___Kunden;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.KundenItem> ___Kunden;
        
    }
    #endregion
    
    #region ArtikelstammItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ArtikelstammItem :
        global::LightSwitchApplication.ArtikelstammItem.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnArtikelnummerChanged()
        {
            this.___OnPropertyChanged("Artikelnummer");
        }
        
        partial void OnArtikelbeschreibungChanged()
        {
            this.___OnPropertyChanged("Artikelbeschreibung");
        }
        
        partial void OnVertriebsnameChanged()
        {
            this.___OnPropertyChanged("Vertriebsname");
        }
        
        partial void OnAnzahl_PKChanged()
        {
            this.___OnPropertyChanged("Anzahl_PK");
        }
        
        partial void OnHK_pro_PKChanged()
        {
            this.___OnPropertyChanged("HK_pro_PK");
        }
        
        partial void OnEK_pro_PKChanged()
        {
            this.___OnPropertyChanged("EK_pro_PK");
        }
        
        partial void OnVK_pro_PKChanged()
        {
            this.___OnPropertyChanged("VK_pro_PK");
        }
        
        partial void OnMargeChanged()
        {
            this.___OnPropertyChanged("Marge");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ArtikelstammItem.DetailsClass.IImplementation.ArtikellisteItem
        {
            get
            {
                return this.ArtikellisteItem;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ArtikellisteItem> __ArtikellisteItem
        {
            get
            {
                if (this.___ArtikellisteItem == null)
                {
                    this.___ArtikellisteItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ArtikellisteItem>(
                        this,
                        "ArtikellisteItem",
                        () => this._ArtikellisteItem,
                        e => global::System.Object.Equals(e.Artikelliste_Artikelstamm, this.Id));
                }
                return this.___ArtikellisteItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ArtikellisteItem> ___ArtikellisteItem;
        
    }
    #endregion
    
    #region Rechnungen
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Rechnungen :
        global::LightSwitchApplication.Rechnungen.DetailsClass.IImplementation
    {
        partial void OnRechnungen_KundenChanged()
        {
            this.___OnPropertyChanged("Rechnungen_Kunden");
            this.___OnPropertyChanged("Kunde");
        }
        
        partial void OnRechnungen_BezahlartItemChanged()
        {
            this.___OnPropertyChanged("Rechnungen_BezahlartItem");
            this.___OnPropertyChanged("BezahlartItem");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnStatusChanged()
        {
            this.___OnPropertyChanged("Status");
        }
        
        partial void OnAuftragsnummerChanged()
        {
            this.___OnPropertyChanged("Auftragsnummer");
        }
        
        partial void OnReferenznummerChanged()
        {
            this.___OnPropertyChanged("Referenznummer");
        }
        
        partial void OnWebshop_IDChanged()
        {
            this.___OnPropertyChanged("Webshop_ID");
        }
        
        partial void OnBestellerChanged()
        {
            this.___OnPropertyChanged("Besteller");
        }
        
        partial void OnBestelldatumChanged()
        {
            this.___OnPropertyChanged("Bestelldatum");
        }
        
        partial void OnLieferdatumChanged()
        {
            this.___OnPropertyChanged("Lieferdatum");
        }
        
        partial void OnLieferscheinnummerChanged()
        {
            this.___OnPropertyChanged("Lieferscheinnummer");
        }
        
        partial void OnRechnungsdatumChanged()
        {
            this.___OnPropertyChanged("Rechnungsdatum");
        }
        
        partial void OnRechnungsnummerChanged()
        {
            this.___OnPropertyChanged("Rechnungsnummer");
        }
        
        partial void OnLieferkostenChanged()
        {
            this.___OnPropertyChanged("Lieferkosten");
        }
        
        partial void OnRequiresProcessingChanged()
        {
            this.___OnPropertyChanged("RequiresProcessing");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Rechnungen.DetailsClass.IImplementation.Kunde
        {
            get
            {
                return this.Kunde;
            }
            set
            {
                this.Kunde = (global::LightSwitchApplication.Implementation.KundenItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.KundenItem> __Kunde
        {
            get
            {
                if (this.___Kunde == null)
                {
                    this.___Kunde = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.KundenItem>(
                        this,
                        "Kunde",
                        new string[] { "Rechnungen_Kunden" },
                        e => global::System.Object.Equals(e.Id, this.Rechnungen_Kunden),
                        () => this._Kunde,
                        e => this._Kunde = e);
                }
                return this.___Kunde;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.KundenItem> ___Kunde;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Rechnungen.DetailsClass.IImplementation.BezahlartItem
        {
            get
            {
                return this.BezahlartItem;
            }
            set
            {
                this.BezahlartItem = (global::LightSwitchApplication.Implementation.BezahlartItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.BezahlartItem> __BezahlartItem
        {
            get
            {
                if (this.___BezahlartItem == null)
                {
                    this.___BezahlartItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.BezahlartItem>(
                        this,
                        "BezahlartItem",
                        new string[] { "Rechnungen_BezahlartItem" },
                        e => global::System.Object.Equals(e.Id, this.Rechnungen_BezahlartItem),
                        () => this._BezahlartItem,
                        e => this._BezahlartItem = e);
                }
                return this.___BezahlartItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.BezahlartItem> ___BezahlartItem;
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Rechnungen.DetailsClass.IImplementation.ArtikellisteCollection
        {
            get
            {
                return this.ArtikellisteCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ArtikellisteItem> __ArtikellisteCollection
        {
            get
            {
                if (this.___ArtikellisteCollection == null)
                {
                    this.___ArtikellisteCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ArtikellisteItem>(
                        this,
                        "ArtikellisteCollection",
                        () => this._ArtikellisteCollection,
                        e => global::System.Object.Equals(e.Artikelliste_Rechnungen, this.Id));
                }
                return this.___ArtikellisteCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.ArtikellisteItem> ___ArtikellisteCollection;
        
    }
    #endregion
    
    #region ArtikellisteItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ArtikellisteItem :
        global::LightSwitchApplication.ArtikellisteItem.DetailsClass.IImplementation
    {
        partial void OnArtikelliste_ArtikelstammChanged()
        {
            this.___OnPropertyChanged("Artikelliste_Artikelstamm");
            this.___OnPropertyChanged("ArtikelstammItem");
        }
        
        partial void OnArtikelliste_RechnungenChanged()
        {
            this.___OnPropertyChanged("Artikelliste_Rechnungen");
            this.___OnPropertyChanged("Rechnungen");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnAnzahlChanged()
        {
            this.___OnPropertyChanged("Anzahl");
        }
        
        partial void OnRabattChanged()
        {
            this.___OnPropertyChanged("Rabatt");
        }
        
        partial void OnPositionInternChanged()
        {
            this.___OnPropertyChanged("PositionIntern");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ArtikellisteItem.DetailsClass.IImplementation.ArtikelstammItem
        {
            get
            {
                return this.ArtikelstammItem;
            }
            set
            {
                this.ArtikelstammItem = (global::LightSwitchApplication.Implementation.ArtikelstammItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ArtikelstammItem> __ArtikelstammItem
        {
            get
            {
                if (this.___ArtikelstammItem == null)
                {
                    this.___ArtikelstammItem = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ArtikelstammItem>(
                        this,
                        "ArtikelstammItem",
                        new string[] { "Artikelliste_Artikelstamm" },
                        e => global::System.Object.Equals(e.Id, this.Artikelliste_Artikelstamm),
                        () => this._ArtikelstammItem,
                        e => this._ArtikelstammItem = e);
                }
                return this.___ArtikelstammItem;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.ArtikelstammItem> ___ArtikelstammItem;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ArtikellisteItem.DetailsClass.IImplementation.Rechnungen
        {
            get
            {
                return this.Rechnungen;
            }
            set
            {
                this.Rechnungen = (global::LightSwitchApplication.Implementation.Rechnungen)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Rechnungen> __Rechnungen
        {
            get
            {
                if (this.___Rechnungen == null)
                {
                    this.___Rechnungen = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Rechnungen>(
                        this,
                        "Rechnungen",
                        new string[] { "Artikelliste_Rechnungen" },
                        e => global::System.Object.Equals(e.Id, this.Artikelliste_Rechnungen),
                        () => this._Rechnungen,
                        e => this._Rechnungen = e);
                }
                return this.___Rechnungen;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.Rechnungen> ___Rechnungen;
        
    }
    #endregion
    
    #region FirmendatenItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class FirmendatenItem :
        global::LightSwitchApplication.FirmendatenItem.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnFirmennameChanged()
        {
            this.___OnPropertyChanged("Firmenname");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnStraßeChanged()
        {
            this.___OnPropertyChanged("Straße");
        }
        
        partial void OnHausnummerChanged()
        {
            this.___OnPropertyChanged("Hausnummer");
        }
        
        partial void OnPLZChanged()
        {
            this.___OnPropertyChanged("PLZ");
        }
        
        partial void OnStadtChanged()
        {
            this.___OnPropertyChanged("Stadt");
        }
        
        partial void OnLandChanged()
        {
            this.___OnPropertyChanged("Land");
        }
        
        partial void OnUstIDChanged()
        {
            this.___OnPropertyChanged("UstID");
        }
        
        partial void OnEMailChanged()
        {
            this.___OnPropertyChanged("EMail");
        }
        
        partial void OnWebseiteChanged()
        {
            this.___OnPropertyChanged("Webseite");
        }
        
    }
    #endregion
    
    #region Meine_DatenItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Meine_DatenItem :
        global::LightSwitchApplication.Meine_DatenItem.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnselfFirmennameChanged()
        {
            this.___OnPropertyChanged("selfFirmenname");
        }
        
        partial void OnselfStraßeChanged()
        {
            this.___OnPropertyChanged("selfStraße");
        }
        
        partial void OnselfHausnummerChanged()
        {
            this.___OnPropertyChanged("selfHausnummer");
        }
        
        partial void OnselfPLZChanged()
        {
            this.___OnPropertyChanged("selfPLZ");
        }
        
        partial void OnselfStadtChanged()
        {
            this.___OnPropertyChanged("selfStadt");
        }
        
        partial void OnselfLandChanged()
        {
            this.___OnPropertyChanged("selfLand");
        }
        
        partial void OnselfUSTIDChanged()
        {
            this.___OnPropertyChanged("selfUSTID");
        }
        
    }
    #endregion
    
    #region AdressenSetItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class AdressenSetItem :
        global::LightSwitchApplication.AdressenSetItem.DetailsClass.IImplementation
    {
        partial void OnKunden_RechnungsadressenChanged()
        {
            this.___OnPropertyChanged("Kunden_Rechnungsadressen");
            this.___OnPropertyChanged("KundenRechnungsadresse");
        }
        
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnNameChanged()
        {
            this.___OnPropertyChanged("Name");
        }
        
        partial void OnzHd_Besteller_optionalChanged()
        {
            this.___OnPropertyChanged("zHd_Besteller_optional");
        }
        
        partial void OnStarßeChanged()
        {
            this.___OnPropertyChanged("Starße");
        }
        
        partial void OnHausnummerChanged()
        {
            this.___OnPropertyChanged("Hausnummer");
        }
        
        partial void OnPLZChanged()
        {
            this.___OnPropertyChanged("PLZ");
        }
        
        partial void OnStadtChanged()
        {
            this.___OnPropertyChanged("Stadt");
        }
        
        partial void OnLandChanged()
        {
            this.___OnPropertyChanged("Land");
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.AdressenSetItem.DetailsClass.IImplementation.KundenRechnungsadresse
        {
            get
            {
                return this.KundenRechnungsadresse;
            }
            set
            {
                this.KundenRechnungsadresse = (global::LightSwitchApplication.Implementation.KundenItem)value;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.KundenItem> __KundenRechnungsadresse
        {
            get
            {
                if (this.___KundenRechnungsadresse == null)
                {
                    this.___KundenRechnungsadresse = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.KundenItem>(
                        this,
                        "KundenRechnungsadresse",
                        new string[] { "Kunden_Rechnungsadressen" },
                        e => global::System.Object.Equals(e.Id, this.Kunden_Rechnungsadressen),
                        () => this._KundenRechnungsadresse,
                        e => this._KundenRechnungsadresse = e);
                }
                return this.___KundenRechnungsadresse;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRef<global::LightSwitchApplication.Implementation.KundenItem> ___KundenRechnungsadresse;
        
    }
    #endregion
    
    #region BezahlartItem
    [global::System.Runtime.Serialization.DataContract(Namespace = "http://schemas.datacontract.org/2004/07/ApplicationData.Implementation")]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class BezahlartItem :
        global::LightSwitchApplication.BezahlartItem.DetailsClass.IImplementation
    {
        partial void OnIdChanged()
        {
            this.___OnPropertyChanged("Id");
        }
        
        partial void OnRowVersionChanged()
        {
            this.___OnPropertyChanged("RowVersion");
        }
        
        partial void OnBezeichnungChanged()
        {
            this.___OnPropertyChanged("Bezeichnung");
        }
        
        partial void OnText_RechnungChanged()
        {
            this.___OnPropertyChanged("Text_Rechnung");
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.BezahlartItem.DetailsClass.IImplementation.RechnungenCollection
        {
            get
            {
                return this.RechnungenCollection;
            }
        }
        
        internal global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Rechnungen> __RechnungenCollection
        {
            get
            {
                if (this.___RechnungenCollection == null)
                {
                    this.___RechnungenCollection = new global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Rechnungen>(
                        this,
                        "RechnungenCollection",
                        () => this._RechnungenCollection,
                        e => global::System.Object.Equals(e.Rechnungen_BezahlartItem, this.Id));
                }
                return this.___RechnungenCollection;
            }
        }
        
        private global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityRefCollection<global::LightSwitchApplication.Implementation.Rechnungen> ___RechnungenCollection;
        
    }
    #endregion
    
    #region ApplicationDataObjectContext
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ApplicationDataObjectContext
    {
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.KundenItem))
            {
                return new global::LightSwitchApplication.Implementation.KundenItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.KundengruppenItem))
            {
                return new global::LightSwitchApplication.Implementation.KundengruppenItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ArtikelstammItem))
            {
                return new global::LightSwitchApplication.Implementation.ArtikelstammItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Rechnungen))
            {
                return new global::LightSwitchApplication.Implementation.Rechnungen();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ArtikellisteItem))
            {
                return new global::LightSwitchApplication.Implementation.ArtikellisteItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.FirmendatenItem))
            {
                return new global::LightSwitchApplication.Implementation.FirmendatenItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Meine_DatenItem))
            {
                return new global::LightSwitchApplication.Implementation.Meine_DatenItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.AdressenSetItem))
            {
                return new global::LightSwitchApplication.Implementation.AdressenSetItem();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.BezahlartItem))
            {
                return new global::LightSwitchApplication.Implementation.BezahlartItem();
            }
            return null;
        }
    }
    #endregion
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class DataServiceFactory :
        global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.ApplicationData();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.ApplicationData))
            {
                return new global::LightSwitchApplication.Implementation.ApplicationDataObjectContext(global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext.CreateServiceUri("../ApplicationData.svc"));
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.KundenItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.KundenItem);
            }
            if (typeof(global::LightSwitchApplication.KundengruppenItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.KundengruppenItem);
            }
            if (typeof(global::LightSwitchApplication.ArtikelstammItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ArtikelstammItem);
            }
            if (typeof(global::LightSwitchApplication.Rechnungen) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Rechnungen);
            }
            if (typeof(global::LightSwitchApplication.ArtikellisteItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ArtikellisteItem);
            }
            if (typeof(global::LightSwitchApplication.FirmendatenItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.FirmendatenItem);
            }
            if (typeof(global::LightSwitchApplication.Meine_DatenItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Meine_DatenItem);
            }
            if (typeof(global::LightSwitchApplication.AdressenSetItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.AdressenSetItem);
            }
            if (typeof(global::LightSwitchApplication.BezahlartItem) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.BezahlartItem);
            }
            return null;
        }
    }
}
