

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class BezahlartItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität BezahlartItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public BezahlartItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public BezahlartItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.BezahlartItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.BezahlartItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BezahlartItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void BezahlartItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.BezahlartItem.DetailsClass.GetValue(this, global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.BezahlartItem.DetailsClass.SetValue(this, global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.BezahlartItem.DetailsClass.GetValue(this, global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.BezahlartItem.DetailsClass.SetValue(this, global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Bezeichnung
        {
            get
            {
                return global::LightSwitchApplication.BezahlartItem.DetailsClass.GetValue(this, global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.Bezeichnung);
            }
            set
            {
                global::LightSwitchApplication.BezahlartItem.DetailsClass.SetValue(this, global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.Bezeichnung, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bezeichnung_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bezeichnung_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Bezeichnung_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Text_Rechnung
        {
            get
            {
                return global::LightSwitchApplication.BezahlartItem.DetailsClass.GetValue(this, global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.Text_Rechnung);
            }
            set
            {
                global::LightSwitchApplication.BezahlartItem.DetailsClass.SetValue(this, global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.Text_Rechnung, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Text_Rechnung_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Text_Rechnung_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Text_Rechnung_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Rechnungen> RechnungenCollection
        {
            get
            {
                return global::LightSwitchApplication.BezahlartItem.DetailsClass.GetValue(this, global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.RechnungenCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Rechnungen> RechnungenCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.BezahlartItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.RechnungenCollection);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.BezahlartItem,
                global::LightSwitchApplication.BezahlartItem.DetailsClass,
                global::LightSwitchApplication.BezahlartItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass>.Entry
                __BezahlartItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.BezahlartItem.DetailsClass.__BezahlartItem_CreateNew,
                    global::LightSwitchApplication.BezahlartItem.DetailsClass.__BezahlartItem_Created,
                    global::LightSwitchApplication.BezahlartItem.DetailsClass.__BezahlartItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.BezahlartItem __BezahlartItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.BezahlartItem> es)
            {
                return new global::LightSwitchApplication.BezahlartItem(es);
            }
            private static void __BezahlartItem_Created(global::LightSwitchApplication.BezahlartItem e)
            {
                e.BezahlartItem_Created();
            }
            private static bool __BezahlartItem_AllowSaveWithErrors(global::LightSwitchApplication.BezahlartItem e)
            {
                bool result = false;
                e.BezahlartItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string> Bezeichnung
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.Bezeichnung) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string> Text_Rechnung
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.Text_Rechnung) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, global::LightSwitchApplication.Rechnungen> RechnungenCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.RechnungenCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, global::LightSwitchApplication.Rechnungen>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Bezeichnung { get; set; }
                new string Text_Rechnung { get; set; }
                new global::System.Collections.IEnumerable RechnungenCollection { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BezahlartItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.BezahlartItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.BezahlartItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.BezahlartItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.BezahlartItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.BezahlartItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.BezahlartItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BezahlartItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.BezahlartItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.BezahlartItem e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.BezahlartItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.BezahlartItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.BezahlartItem.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.BezahlartItem e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string>.Entry
                    Bezeichnung = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string>.Entry(
                        "Bezeichnung",
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Bezeichnung_Stub,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Bezeichnung_ComputeIsReadOnly,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Bezeichnung_Validate,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Bezeichnung_GetImplementationValue,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Bezeichnung_SetImplementationValue,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Bezeichnung_OnValueChanged);
                private static void _Bezeichnung_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BezahlartItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.BezahlartItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Bezeichnung, sf);
                }
                private static bool _Bezeichnung_ComputeIsReadOnly(global::LightSwitchApplication.BezahlartItem e)
                {
                    bool result = false;
                    e.Bezeichnung_IsReadOnly(ref result);
                    return result;
                }
                private static void _Bezeichnung_Validate(global::LightSwitchApplication.BezahlartItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Bezeichnung_Validate(r);
                }
                private static string _Bezeichnung_GetImplementationValue(global::LightSwitchApplication.BezahlartItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Bezeichnung;
                }
                private static void _Bezeichnung_SetImplementationValue(global::LightSwitchApplication.BezahlartItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Bezeichnung = v;
                }
                private static void _Bezeichnung_OnValueChanged(global::LightSwitchApplication.BezahlartItem e)
                {
                    e.Bezeichnung_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string>.Entry
                    Text_Rechnung = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string>.Entry(
                        "Text_Rechnung",
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Text_Rechnung_Stub,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Text_Rechnung_ComputeIsReadOnly,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Text_Rechnung_Validate,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Text_Rechnung_GetImplementationValue,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Text_Rechnung_SetImplementationValue,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._Text_Rechnung_OnValueChanged);
                private static void _Text_Rechnung_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BezahlartItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.BezahlartItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Text_Rechnung, sf);
                }
                private static bool _Text_Rechnung_ComputeIsReadOnly(global::LightSwitchApplication.BezahlartItem e)
                {
                    bool result = false;
                    e.Text_Rechnung_IsReadOnly(ref result);
                    return result;
                }
                private static void _Text_Rechnung_Validate(global::LightSwitchApplication.BezahlartItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Text_Rechnung_Validate(r);
                }
                private static string _Text_Rechnung_GetImplementationValue(global::LightSwitchApplication.BezahlartItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Text_Rechnung;
                }
                private static void _Text_Rechnung_SetImplementationValue(global::LightSwitchApplication.BezahlartItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Text_Rechnung = v;
                }
                private static void _Text_Rechnung_OnValueChanged(global::LightSwitchApplication.BezahlartItem e)
                {
                    e.Text_Rechnung_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, global::LightSwitchApplication.Rechnungen>.Entry
                    RechnungenCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, global::LightSwitchApplication.Rechnungen>.Entry(
                        "RechnungenCollection",
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._RechnungenCollection_Stub,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._RechnungenCollection_GetReferencedEntities,
                        global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties._RechnungenCollection_GetEntityCollection);
                private static void _RechnungenCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.BezahlartItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, global::LightSwitchApplication.Rechnungen>.Data> c, global::LightSwitchApplication.BezahlartItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RechnungenCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Rechnungen> _RechnungenCollection_GetReferencedEntities(global::LightSwitchApplication.BezahlartItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Rechnungen, global::LightSwitchApplication.Rechnungen.DetailsClass>(global::LightSwitchApplication.BezahlartItem.DetailsClass.PropertySetProperties.RechnungenCollection, ref d._RechnungenCollection);
                }
                private static global::System.Collections.IEnumerable _RechnungenCollection_GetEntityCollection(global::LightSwitchApplication.BezahlartItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RechnungenCollection;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string>.Data _Bezeichnung;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, string>.Data _Text_Rechnung;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.BezahlartItem, global::LightSwitchApplication.BezahlartItem.DetailsClass, global::LightSwitchApplication.Rechnungen>.Data _RechnungenCollection;
            
        }
    
        #endregion
    }
    
    #endregion
}
