

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class MailSettings : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität MailSettings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public MailSettings()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public MailSettings(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.MailSettings> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.MailSettings.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MailSettings_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MailSettings_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.MailSettings.DetailsClass.GetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.MailSettings.DetailsClass.SetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.MailSettings.DetailsClass.GetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.MailSettings.DetailsClass.SetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SmtpServer
        {
            get
            {
                return global::LightSwitchApplication.MailSettings.DetailsClass.GetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.SmtpServer);
            }
            set
            {
                global::LightSwitchApplication.MailSettings.DetailsClass.SetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.SmtpServer, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SmtpServer_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SmtpServer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SmtpServer_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Port
        {
            get
            {
                return global::LightSwitchApplication.MailSettings.DetailsClass.GetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Port);
            }
            set
            {
                global::LightSwitchApplication.MailSettings.DetailsClass.SetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Port, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Port_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Port_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Port_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Username
        {
            get
            {
                return global::LightSwitchApplication.MailSettings.DetailsClass.GetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Username);
            }
            set
            {
                global::LightSwitchApplication.MailSettings.DetailsClass.SetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Username, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Username_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Username_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Username_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Password
        {
            get
            {
                return global::LightSwitchApplication.MailSettings.DetailsClass.GetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Password);
            }
            set
            {
                global::LightSwitchApplication.MailSettings.DetailsClass.SetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Password, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SenderAddress
        {
            get
            {
                return global::LightSwitchApplication.MailSettings.DetailsClass.GetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.SenderAddress);
            }
            set
            {
                global::LightSwitchApplication.MailSettings.DetailsClass.SetValue(this, global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.SenderAddress, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SenderAddress_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SenderAddress_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SenderAddress_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.MailSettings,
                global::LightSwitchApplication.MailSettings.DetailsClass,
                global::LightSwitchApplication.MailSettings.DetailsClass.IImplementation,
                global::LightSwitchApplication.MailSettings.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass>.Entry
                __MailSettingsEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass>.Entry(
                    global::LightSwitchApplication.MailSettings.DetailsClass.__MailSettings_CreateNew,
                    global::LightSwitchApplication.MailSettings.DetailsClass.__MailSettings_Created,
                    global::LightSwitchApplication.MailSettings.DetailsClass.__MailSettings_AllowSaveWithErrors);
            private static global::LightSwitchApplication.MailSettings __MailSettings_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.MailSettings> es)
            {
                return new global::LightSwitchApplication.MailSettings(es);
            }
            private static void __MailSettings_Created(global::LightSwitchApplication.MailSettings e)
            {
                e.MailSettings_Created();
            }
            private static bool __MailSettings_AllowSaveWithErrors(global::LightSwitchApplication.MailSettings e)
            {
                bool result = false;
                e.MailSettings_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.MailSettings.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string> SmtpServer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.SmtpServer) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int> Port
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Port) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string> Username
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Username) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string> Password
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.Password) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string> SenderAddress
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties.SenderAddress) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string SmtpServer { get; set; }
                new int Port { get; set; }
                new string Username { get; set; }
                new string Password { get; set; }
                new string SenderAddress { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailSettings.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int>.Data> c, global::LightSwitchApplication.MailSettings.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.MailSettings e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.MailSettings e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.MailSettings e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailSettings.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.MailSettings.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.MailSettings e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.MailSettings e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.MailSettings e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Entry
                    SmtpServer = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Entry(
                        "SmtpServer",
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SmtpServer_Stub,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SmtpServer_ComputeIsReadOnly,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SmtpServer_Validate,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SmtpServer_GetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SmtpServer_SetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SmtpServer_OnValueChanged);
                private static void _SmtpServer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailSettings.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Data> c, global::LightSwitchApplication.MailSettings.DetailsClass d, object sf)
                {
                    c(d, ref d._SmtpServer, sf);
                }
                private static bool _SmtpServer_ComputeIsReadOnly(global::LightSwitchApplication.MailSettings e)
                {
                    bool result = false;
                    e.SmtpServer_IsReadOnly(ref result);
                    return result;
                }
                private static void _SmtpServer_Validate(global::LightSwitchApplication.MailSettings e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SmtpServer_Validate(r);
                }
                private static string _SmtpServer_GetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d)
                {
                    return d.ImplementationEntity.SmtpServer;
                }
                private static void _SmtpServer_SetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SmtpServer = v;
                }
                private static void _SmtpServer_OnValueChanged(global::LightSwitchApplication.MailSettings e)
                {
                    e.SmtpServer_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int>.Entry
                    Port = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int>.Entry(
                        "Port",
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Port_Stub,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Port_ComputeIsReadOnly,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Port_Validate,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Port_GetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Port_SetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Port_OnValueChanged);
                private static void _Port_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailSettings.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int>.Data> c, global::LightSwitchApplication.MailSettings.DetailsClass d, object sf)
                {
                    c(d, ref d._Port, sf);
                }
                private static bool _Port_ComputeIsReadOnly(global::LightSwitchApplication.MailSettings e)
                {
                    bool result = false;
                    e.Port_IsReadOnly(ref result);
                    return result;
                }
                private static void _Port_Validate(global::LightSwitchApplication.MailSettings e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Port_Validate(r);
                }
                private static int _Port_GetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d)
                {
                    return d.ImplementationEntity.Port;
                }
                private static void _Port_SetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Port = v;
                }
                private static void _Port_OnValueChanged(global::LightSwitchApplication.MailSettings e)
                {
                    e.Port_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Entry
                    Username = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Entry(
                        "Username",
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Username_Stub,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Username_ComputeIsReadOnly,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Username_Validate,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Username_GetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Username_SetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Username_OnValueChanged);
                private static void _Username_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailSettings.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Data> c, global::LightSwitchApplication.MailSettings.DetailsClass d, object sf)
                {
                    c(d, ref d._Username, sf);
                }
                private static bool _Username_ComputeIsReadOnly(global::LightSwitchApplication.MailSettings e)
                {
                    bool result = false;
                    e.Username_IsReadOnly(ref result);
                    return result;
                }
                private static void _Username_Validate(global::LightSwitchApplication.MailSettings e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Username_Validate(r);
                }
                private static string _Username_GetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d)
                {
                    return d.ImplementationEntity.Username;
                }
                private static void _Username_SetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Username = v;
                }
                private static void _Username_OnValueChanged(global::LightSwitchApplication.MailSettings e)
                {
                    e.Username_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Entry
                    Password = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Entry(
                        "Password",
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Password_Stub,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Password_ComputeIsReadOnly,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Password_Validate,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Password_GetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Password_SetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._Password_OnValueChanged);
                private static void _Password_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailSettings.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Data> c, global::LightSwitchApplication.MailSettings.DetailsClass d, object sf)
                {
                    c(d, ref d._Password, sf);
                }
                private static bool _Password_ComputeIsReadOnly(global::LightSwitchApplication.MailSettings e)
                {
                    bool result = false;
                    e.Password_IsReadOnly(ref result);
                    return result;
                }
                private static void _Password_Validate(global::LightSwitchApplication.MailSettings e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Password_Validate(r);
                }
                private static string _Password_GetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d)
                {
                    return d.ImplementationEntity.Password;
                }
                private static void _Password_SetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Password = v;
                }
                private static void _Password_OnValueChanged(global::LightSwitchApplication.MailSettings e)
                {
                    e.Password_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Entry
                    SenderAddress = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Entry(
                        "SenderAddress",
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SenderAddress_Stub,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SenderAddress_ComputeIsReadOnly,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SenderAddress_Validate,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SenderAddress_GetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SenderAddress_SetImplementationValue,
                        global::LightSwitchApplication.MailSettings.DetailsClass.PropertySetProperties._SenderAddress_OnValueChanged);
                private static void _SenderAddress_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MailSettings.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Data> c, global::LightSwitchApplication.MailSettings.DetailsClass d, object sf)
                {
                    c(d, ref d._SenderAddress, sf);
                }
                private static bool _SenderAddress_ComputeIsReadOnly(global::LightSwitchApplication.MailSettings e)
                {
                    bool result = false;
                    e.SenderAddress_IsReadOnly(ref result);
                    return result;
                }
                private static void _SenderAddress_Validate(global::LightSwitchApplication.MailSettings e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SenderAddress_Validate(r);
                }
                private static string _SenderAddress_GetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d)
                {
                    return d.ImplementationEntity.SenderAddress;
                }
                private static void _SenderAddress_SetImplementationValue(global::LightSwitchApplication.MailSettings.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SenderAddress = v;
                }
                private static void _SenderAddress_OnValueChanged(global::LightSwitchApplication.MailSettings e)
                {
                    e.SenderAddress_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Data _SmtpServer;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, int>.Data _Port;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Data _Username;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Data _Password;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.MailSettings, global::LightSwitchApplication.MailSettings.DetailsClass, string>.Data _SenderAddress;
            
        }
    
        #endregion
    }
    
    #endregion
}
