

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class AdressenSetItem : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität AdressenSetItem.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public AdressenSetItem()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public AdressenSetItem(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.AdressenSetItem> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.AdressenSetItem.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AdressenSetItem_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void AdressenSetItem_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Anrede
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Anrede);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Anrede, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Anrede_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Anrede_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Anrede_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string zHd_Besteller_optional
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.zHd_Besteller_optional);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.zHd_Besteller_optional, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void zHd_Besteller_optional_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void zHd_Besteller_optional_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void zHd_Besteller_optional_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Straße
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Straße);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Straße, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Straße_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Straße_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Straße_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Hausnummer
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Hausnummer);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Hausnummer, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hausnummer_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hausnummer_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Hausnummer_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string PLZ
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.PLZ);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.PLZ, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PLZ_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PLZ_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PLZ_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Stadt
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Stadt);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Stadt, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Stadt_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Stadt_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Stadt_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Land
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Land);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Land, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Land_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Land_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Land_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.KundenItem KundenRechnungsadresse
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.KundenRechnungsadresse);
            }
            set
            {
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.SetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.KundenRechnungsadresse, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KundenRechnungsadresse_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KundenRechnungsadresse_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void KundenRechnungsadresse_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Rechnungen> RechnungenCollection
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetValue(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.RechnungenCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Rechnungen> RechnungenCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.AdressenSetItem.DetailsClass.GetQuery(this, global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.RechnungenCollection);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.AdressenSetItem,
                global::LightSwitchApplication.AdressenSetItem.DetailsClass,
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.IImplementation,
                global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass>.Entry
                __AdressenSetItemEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass>.Entry(
                    global::LightSwitchApplication.AdressenSetItem.DetailsClass.__AdressenSetItem_CreateNew,
                    global::LightSwitchApplication.AdressenSetItem.DetailsClass.__AdressenSetItem_Created,
                    global::LightSwitchApplication.AdressenSetItem.DetailsClass.__AdressenSetItem_AllowSaveWithErrors);
            private static global::LightSwitchApplication.AdressenSetItem __AdressenSetItem_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.AdressenSetItem> es)
            {
                return new global::LightSwitchApplication.AdressenSetItem(es);
            }
            private static void __AdressenSetItem_Created(global::LightSwitchApplication.AdressenSetItem e)
            {
                e.AdressenSetItem_Created();
            }
            private static bool __AdressenSetItem_AllowSaveWithErrors(global::LightSwitchApplication.AdressenSetItem e)
            {
                bool result = false;
                e.AdressenSetItem_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string> Anrede
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Anrede) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string> zHd_Besteller_optional
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.zHd_Besteller_optional) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string> Straße
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Straße) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string> Hausnummer
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Hausnummer) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string> PLZ
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.PLZ) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string> Stadt
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Stadt) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string> Land
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.Land) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.KundenItem> KundenRechnungsadresse
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.KundenRechnungsadresse) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.KundenItem>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.Rechnungen> RechnungenCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.RechnungenCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.Rechnungen>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new string Anrede { get; set; }
                new string Name { get; set; }
                new string zHd_Besteller_optional { get; set; }
                new string Straße { get; set; }
                new string Hausnummer { get; set; }
                new string PLZ { get; set; }
                new string Stadt { get; set; }
                new string Land { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation KundenRechnungsadresse { get; set; }
                new global::System.Collections.IEnumerable RechnungenCollection { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, int>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry
                    Anrede = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry(
                        "Anrede",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Anrede_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Anrede_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Anrede_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Anrede_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Anrede_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Anrede_OnValueChanged);
                private static void _Anrede_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Anrede, sf);
                }
                private static bool _Anrede_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.Anrede_IsReadOnly(ref result);
                    return result;
                }
                private static void _Anrede_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Anrede_Validate(r);
                }
                private static string _Anrede_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Anrede;
                }
                private static void _Anrede_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Anrede = v;
                }
                private static void _Anrede_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.Anrede_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry
                    zHd_Besteller_optional = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry(
                        "zHd_Besteller_optional",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._zHd_Besteller_optional_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._zHd_Besteller_optional_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._zHd_Besteller_optional_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._zHd_Besteller_optional_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._zHd_Besteller_optional_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._zHd_Besteller_optional_OnValueChanged);
                private static void _zHd_Besteller_optional_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._zHd_Besteller_optional, sf);
                }
                private static bool _zHd_Besteller_optional_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.zHd_Besteller_optional_IsReadOnly(ref result);
                    return result;
                }
                private static void _zHd_Besteller_optional_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.zHd_Besteller_optional_Validate(r);
                }
                private static string _zHd_Besteller_optional_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.zHd_Besteller_optional;
                }
                private static void _zHd_Besteller_optional_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.zHd_Besteller_optional = v;
                }
                private static void _zHd_Besteller_optional_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.zHd_Besteller_optional_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry
                    Straße = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry(
                        "Straße",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Straße_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Straße_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Straße_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Straße_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Straße_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Straße_OnValueChanged);
                private static void _Straße_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Straße, sf);
                }
                private static bool _Straße_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.Straße_IsReadOnly(ref result);
                    return result;
                }
                private static void _Straße_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Straße_Validate(r);
                }
                private static string _Straße_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Straße;
                }
                private static void _Straße_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Straße = v;
                }
                private static void _Straße_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.Straße_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry
                    Hausnummer = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry(
                        "Hausnummer",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Hausnummer_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Hausnummer_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Hausnummer_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Hausnummer_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Hausnummer_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Hausnummer_OnValueChanged);
                private static void _Hausnummer_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Hausnummer, sf);
                }
                private static bool _Hausnummer_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.Hausnummer_IsReadOnly(ref result);
                    return result;
                }
                private static void _Hausnummer_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Hausnummer_Validate(r);
                }
                private static string _Hausnummer_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Hausnummer;
                }
                private static void _Hausnummer_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Hausnummer = v;
                }
                private static void _Hausnummer_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.Hausnummer_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry
                    PLZ = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry(
                        "PLZ",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._PLZ_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._PLZ_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._PLZ_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._PLZ_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._PLZ_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._PLZ_OnValueChanged);
                private static void _PLZ_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._PLZ, sf);
                }
                private static bool _PLZ_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.PLZ_IsReadOnly(ref result);
                    return result;
                }
                private static void _PLZ_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.PLZ_Validate(r);
                }
                private static string _PLZ_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.PLZ;
                }
                private static void _PLZ_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.PLZ = v;
                }
                private static void _PLZ_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.PLZ_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry
                    Stadt = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry(
                        "Stadt",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Stadt_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Stadt_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Stadt_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Stadt_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Stadt_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Stadt_OnValueChanged);
                private static void _Stadt_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Stadt, sf);
                }
                private static bool _Stadt_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.Stadt_IsReadOnly(ref result);
                    return result;
                }
                private static void _Stadt_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Stadt_Validate(r);
                }
                private static string _Stadt_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Stadt;
                }
                private static void _Stadt_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Stadt = v;
                }
                private static void _Stadt_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.Stadt_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry
                    Land = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Entry(
                        "Land",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Land_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Land_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Land_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Land_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Land_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._Land_OnValueChanged);
                private static void _Land_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._Land, sf);
                }
                private static bool _Land_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.Land_IsReadOnly(ref result);
                    return result;
                }
                private static void _Land_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Land_Validate(r);
                }
                private static string _Land_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.Land;
                }
                private static void _Land_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Land = v;
                }
                private static void _Land_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.Land_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.KundenItem>.Entry
                    KundenRechnungsadresse = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.KundenItem>.Entry(
                        "KundenRechnungsadresse",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._KundenRechnungsadresse_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._KundenRechnungsadresse_ComputeIsReadOnly,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._KundenRechnungsadresse_Validate,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._KundenRechnungsadresse_GetCoreImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._KundenRechnungsadresse_GetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._KundenRechnungsadresse_SetImplementationValue,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._KundenRechnungsadresse_Refresh,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._KundenRechnungsadresse_OnValueChanged);
                private static void _KundenRechnungsadresse_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.KundenItem>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._KundenRechnungsadresse, sf);
                }
                private static bool _KundenRechnungsadresse_ComputeIsReadOnly(global::LightSwitchApplication.AdressenSetItem e)
                {
                    bool result = false;
                    e.KundenRechnungsadresse_IsReadOnly(ref result);
                    return result;
                }
                private static void _KundenRechnungsadresse_Validate(global::LightSwitchApplication.AdressenSetItem e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.KundenRechnungsadresse_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _KundenRechnungsadresse_GetCoreImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.KundenRechnungsadresse;
                }
                private static global::LightSwitchApplication.KundenItem _KundenRechnungsadresse_GetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.KundenItem, global::LightSwitchApplication.KundenItem.DetailsClass>(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.KundenRechnungsadresse, ref d._KundenRechnungsadresse);
                }
                private static void _KundenRechnungsadresse_SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass d, global::LightSwitchApplication.KundenItem v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.KundenRechnungsadresse, ref d._KundenRechnungsadresse, (i, ev) => i.KundenRechnungsadresse = ev, v);
                }
                private static void _KundenRechnungsadresse_Refresh(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.KundenRechnungsadresse, ref d._KundenRechnungsadresse);
                }
                private static void _KundenRechnungsadresse_OnValueChanged(global::LightSwitchApplication.AdressenSetItem e)
                {
                    e.KundenRechnungsadresse_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.Rechnungen>.Entry
                    RechnungenCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.Rechnungen>.Entry(
                        "RechnungenCollection",
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._RechnungenCollection_Stub,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._RechnungenCollection_GetReferencedEntities,
                        global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties._RechnungenCollection_GetEntityCollection);
                private static void _RechnungenCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.Rechnungen>.Data> c, global::LightSwitchApplication.AdressenSetItem.DetailsClass d, object sf)
                {
                    c(d, ref d._RechnungenCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Rechnungen> _RechnungenCollection_GetReferencedEntities(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Rechnungen, global::LightSwitchApplication.Rechnungen.DetailsClass>(global::LightSwitchApplication.AdressenSetItem.DetailsClass.PropertySetProperties.RechnungenCollection, ref d._RechnungenCollection);
                }
                private static global::System.Collections.IEnumerable _RechnungenCollection_GetEntityCollection(global::LightSwitchApplication.AdressenSetItem.DetailsClass d)
                {
                    return d.ImplementationEntity.RechnungenCollection;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data _Anrede;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data _zHd_Besteller_optional;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data _Straße;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data _Hausnummer;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data _PLZ;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data _Stadt;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, string>.Data _Land;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.KundenItem>.Data _KundenRechnungsadresse;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.AdressenSetItem, global::LightSwitchApplication.AdressenSetItem.DetailsClass, global::LightSwitchApplication.Rechnungen>.Data _RechnungenCollection;
            
        }
    
        #endregion
    }
    
    #endregion
}
