

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// Keine modellierte Beschreibung verfügbar
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class OutgoingMail : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initialisiert eine neue Instanz der Entität OutgoingMail.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public OutgoingMail()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public OutgoingMail(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.OutgoingMail> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.OutgoingMail.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OutgoingMail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OutgoingMail_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Ruft das Application-Objekt für diese Anwendung ab. Das Application-Objekt stellt Zugriff auf aktive Bildschirme, Methoden zum Öffnen von Bildschirmen sowie Zugriff auf den aktuellen Benutzer bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Ruft den übergeordneten Datenarbeitsbereich ab. Der Datenarbeitsbereich stellt Zugriff auf alle Datenquellen in der Anwendung bereit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.OutgoingMail.DetailsClass.GetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.OutgoingMail.DetailsClass.SetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.OutgoingMail.DetailsClass.GetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.OutgoingMail.DetailsClass.SetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> Sended
        {
            get
            {
                return global::LightSwitchApplication.OutgoingMail.DetailsClass.GetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Sended);
            }
            set
            {
                global::LightSwitchApplication.OutgoingMail.DetailsClass.SetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Sended, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sended_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sended_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Sended_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Recipient
        {
            get
            {
                return global::LightSwitchApplication.OutgoingMail.DetailsClass.GetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Recipient);
            }
            set
            {
                global::LightSwitchApplication.OutgoingMail.DetailsClass.SetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Recipient, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Recipient_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Recipient_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Recipient_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Subject
        {
            get
            {
                return global::LightSwitchApplication.OutgoingMail.DetailsClass.GetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Subject);
            }
            set
            {
                global::LightSwitchApplication.OutgoingMail.DetailsClass.SetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Subject, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subject_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subject_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Subject_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Body
        {
            get
            {
                return global::LightSwitchApplication.OutgoingMail.DetailsClass.GetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Body);
            }
            set
            {
                global::LightSwitchApplication.OutgoingMail.DetailsClass.SetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Body, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Body_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Body_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Body_Changed();

        /// <summary>
        /// Keine modellierte Beschreibung verfügbar
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Result
        {
            get
            {
                return global::LightSwitchApplication.OutgoingMail.DetailsClass.GetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Result);
            }
            set
            {
                global::LightSwitchApplication.OutgoingMail.DetailsClass.SetValue(this, global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Result, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Result_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Result_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Result_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.OutgoingMail,
                global::LightSwitchApplication.OutgoingMail.DetailsClass,
                global::LightSwitchApplication.OutgoingMail.DetailsClass.IImplementation,
                global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass>.Entry
                __OutgoingMailEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass>.Entry(
                    global::LightSwitchApplication.OutgoingMail.DetailsClass.__OutgoingMail_CreateNew,
                    global::LightSwitchApplication.OutgoingMail.DetailsClass.__OutgoingMail_Created,
                    global::LightSwitchApplication.OutgoingMail.DetailsClass.__OutgoingMail_AllowSaveWithErrors);
            private static global::LightSwitchApplication.OutgoingMail __OutgoingMail_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.OutgoingMail> es)
            {
                return new global::LightSwitchApplication.OutgoingMail(es);
            }
            private static void __OutgoingMail_Created(global::LightSwitchApplication.OutgoingMail e)
            {
                e.OutgoingMail_Created();
            }
            private static bool __OutgoingMail_AllowSaveWithErrors(global::LightSwitchApplication.OutgoingMail e)
            {
                bool result = false;
                e.OutgoingMail_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, global::System.Nullable<global::System.DateTime>> Sended
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Sended) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string> Recipient
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Recipient) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string> Subject
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Subject) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string> Body
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Body) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string> Result
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties.Result) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.Nullable<global::System.DateTime> Sended { get; set; }
                new string Recipient { get; set; }
                new string Subject { get; set; }
                new string Body { get; set; }
                new string Result { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OutgoingMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, int>.Data> c, global::LightSwitchApplication.OutgoingMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.OutgoingMail e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.OutgoingMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.OutgoingMail e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OutgoingMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.OutgoingMail.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.OutgoingMail e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.OutgoingMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.OutgoingMail e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    Sended = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "Sended",
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Sended_Stub,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Sended_ComputeIsReadOnly,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Sended_Validate,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Sended_GetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Sended_SetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Sended_OnValueChanged);
                private static void _Sended_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OutgoingMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.OutgoingMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Sended, sf);
                }
                private static bool _Sended_ComputeIsReadOnly(global::LightSwitchApplication.OutgoingMail e)
                {
                    bool result = false;
                    e.Sended_IsReadOnly(ref result);
                    return result;
                }
                private static void _Sended_Validate(global::LightSwitchApplication.OutgoingMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Sended_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _Sended_GetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Sended;
                }
                private static void _Sended_SetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d, global::System.Nullable<global::System.DateTime> v)
                {
                    d.ImplementationEntity.Sended = global::LightSwitchApplication.OutgoingMail.DetailsClass.TruncateDate(v);
                }
                private static void _Sended_OnValueChanged(global::LightSwitchApplication.OutgoingMail e)
                {
                    e.Sended_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Entry
                    Recipient = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Entry(
                        "Recipient",
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Recipient_Stub,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Recipient_ComputeIsReadOnly,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Recipient_Validate,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Recipient_GetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Recipient_SetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Recipient_OnValueChanged);
                private static void _Recipient_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OutgoingMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Data> c, global::LightSwitchApplication.OutgoingMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Recipient, sf);
                }
                private static bool _Recipient_ComputeIsReadOnly(global::LightSwitchApplication.OutgoingMail e)
                {
                    bool result = false;
                    e.Recipient_IsReadOnly(ref result);
                    return result;
                }
                private static void _Recipient_Validate(global::LightSwitchApplication.OutgoingMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Recipient_Validate(r);
                }
                private static string _Recipient_GetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Recipient;
                }
                private static void _Recipient_SetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Recipient = v;
                }
                private static void _Recipient_OnValueChanged(global::LightSwitchApplication.OutgoingMail e)
                {
                    e.Recipient_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Entry
                    Subject = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Entry(
                        "Subject",
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Subject_Stub,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Subject_ComputeIsReadOnly,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Subject_Validate,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Subject_GetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Subject_SetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Subject_OnValueChanged);
                private static void _Subject_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OutgoingMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Data> c, global::LightSwitchApplication.OutgoingMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Subject, sf);
                }
                private static bool _Subject_ComputeIsReadOnly(global::LightSwitchApplication.OutgoingMail e)
                {
                    bool result = false;
                    e.Subject_IsReadOnly(ref result);
                    return result;
                }
                private static void _Subject_Validate(global::LightSwitchApplication.OutgoingMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Subject_Validate(r);
                }
                private static string _Subject_GetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Subject;
                }
                private static void _Subject_SetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Subject = v;
                }
                private static void _Subject_OnValueChanged(global::LightSwitchApplication.OutgoingMail e)
                {
                    e.Subject_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Entry
                    Body = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Entry(
                        "Body",
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Body_Stub,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Body_ComputeIsReadOnly,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Body_Validate,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Body_GetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Body_SetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Body_OnValueChanged);
                private static void _Body_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OutgoingMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Data> c, global::LightSwitchApplication.OutgoingMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Body, sf);
                }
                private static bool _Body_ComputeIsReadOnly(global::LightSwitchApplication.OutgoingMail e)
                {
                    bool result = false;
                    e.Body_IsReadOnly(ref result);
                    return result;
                }
                private static void _Body_Validate(global::LightSwitchApplication.OutgoingMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Body_Validate(r);
                }
                private static string _Body_GetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Body;
                }
                private static void _Body_SetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Body = v;
                }
                private static void _Body_OnValueChanged(global::LightSwitchApplication.OutgoingMail e)
                {
                    e.Body_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Entry
                    Result = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Entry(
                        "Result",
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Result_Stub,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Result_ComputeIsReadOnly,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Result_Validate,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Result_GetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Result_SetImplementationValue,
                        global::LightSwitchApplication.OutgoingMail.DetailsClass.PropertySetProperties._Result_OnValueChanged);
                private static void _Result_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OutgoingMail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Data> c, global::LightSwitchApplication.OutgoingMail.DetailsClass d, object sf)
                {
                    c(d, ref d._Result, sf);
                }
                private static bool _Result_ComputeIsReadOnly(global::LightSwitchApplication.OutgoingMail e)
                {
                    bool result = false;
                    e.Result_IsReadOnly(ref result);
                    return result;
                }
                private static void _Result_Validate(global::LightSwitchApplication.OutgoingMail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Result_Validate(r);
                }
                private static string _Result_GetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d)
                {
                    return d.ImplementationEntity.Result;
                }
                private static void _Result_SetImplementationValue(global::LightSwitchApplication.OutgoingMail.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Result = v;
                }
                private static void _Result_OnValueChanged(global::LightSwitchApplication.OutgoingMail e)
                {
                    e.Result_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _Sended;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Data _Recipient;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Data _Subject;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Data _Body;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OutgoingMail, global::LightSwitchApplication.OutgoingMail.DetailsClass, string>.Data _Result;
            
        }
    
        #endregion
    }
    
    #endregion
}
